# Generated by Django 5.2 on 2026-05-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='brand',
            name='site_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='booklet_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_rutube',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_youtube',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]