# Generated by Django 5.2 on 2026-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_merge_polyprom_and_disable_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('split_system', 'Сплит-система'), ('accessory', 'Аксессуар / не для розницы'), ('multi_split_block', 'Компонент мульти-сплит')], db_index=True, default='split_system', help_text='Считается один раз при синке по title через apps.catalog.classify.classify_title — вместо regex-фильтра (NON_RETAIL_Q/MULTI_SPLIT_BLOCK_Q), пересчитываемого на каждый catalog-запрос.', max_length=20),
        ),
    ]
