# Generated by Django 5.2 on 2026-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heating_min_temp',
            field=models.SmallIntegerField(blank=True, db_index=True, help_text='Нижняя граница работы на обогрев. Считается при синке из tech_values (у трёх поставщиков три разных названия характеристики) — см. apps.catalog.heating. Не парсится строкой на каждый запрос, иначе full scan на каждый заход в каталог.', null=True, verbose_name='Мин. температура обогрева, °C'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_heat_pump',
            field=models.BooleanField(db_index=True, default=False, help_text='Поставщик сам назвал товар тепловым насосом: категория Rusklimat «Тепловые насосы...» или характеристика Бриза «Тепловой насос: да». Товары с этим флагом попадают в подборку независимо от heating_min_temp.', verbose_name='Тепловой насос (по данным поставщика)'),
        ),
    ]
